### ISSUE TITLE
License

### ISSUE THREAD

**Issue by prasastoadi** [jayvdb/anyhttp#4]
Hi, i see this repo has 2 files that included license in those files.
setup.py
`anyhttp/__init__.py`

```
# Distributed under the terms of the MIT license.
```

But this repo doesn't have dedicated file to tell user about the license. I suggest you to create a file named 'LICENSE' and placed in the root directory. It is easier to user to recognize the license of this library.

**Comment by jayvdb** [comment]
Please send a PR with MIT license.  I will be most grateful.

**Comment by jayvdb** [comment]
Fixed in #5 .
Makasih.
